"""
Node: generate_steps
Takes approved Gherkin scenarios and generates:
  1. A .feature file
  2. Python Behave step definitions
"""

import os
from pathlib import Path

from langchain_core.messages import HumanMessage
from rich.console import Console
from rich.panel import Panel
from rich.syntax import Syntax

from agent.state import AgentState, Scenario
from agent.llm import get_llm

console = Console()

PROMPT_PATH = Path(__file__).parent.parent.parent / "prompts" / "steps_prompt.txt"
FEATURES_DIR = Path(__file__).parent.parent.parent / "features"
STEPS_DIR = FEATURES_DIR / "steps"


def generate_steps_node(state: AgentState) -> AgentState:
    """
    LangGraph node: generates .feature file and Python step definitions
    for all approved scenarios.
    """
    console.print(Panel("[bold cyan]🤖 Generating feature file and step definitions...[/bold cyan]"))

    approved = state.get("approved_scenarios", [])
    if not approved:
        return {
            **state,
            "error": "No approved scenarios to generate steps for.",
            "current_node": "generate_steps"
        }

    # --- 1. Write the .feature file ---
    feature_content = _build_feature_file(approved, state.get("api_spec", ""))
    FEATURES_DIR.mkdir(parents=True, exist_ok=True)
    STEPS_DIR.mkdir(parents=True, exist_ok=True)

    feature_path = FEATURES_DIR / "generated.feature"
    feature_path.write_text(feature_content, encoding="utf-8")
    console.print(f"[green]✅ Feature file written: {feature_path}[/green]")

    # --- 2. Generate step definitions via LLM ---
    gherkin_combined = "\n\n".join(
        f"# Scenario {s['id']}: {s['title']}\n{s['gherkin']}"
        for s in approved
    )

    base_url = _extract_base_url(state.get("api_spec", ""))

    prompt_template = PROMPT_PATH.read_text()
    prompt = prompt_template.format(
        gherkin_scenarios=gherkin_combined,
        base_url=base_url
    )

    llm = get_llm()

    try:
        response = llm.invoke([HumanMessage(content=prompt)])
        raw_code = response.content.strip()

        # Strip markdown code fences if present
        if raw_code.startswith("```"):
            lines = raw_code.splitlines()
            # Remove first line (```python) and last line (```)
            raw_code = "\n".join(lines[1:-1])

        # Write step definitions
        steps_path = STEPS_DIR / "generated_steps.py"
        steps_path.write_text(raw_code, encoding="utf-8")
        console.print(f"[green]✅ Step definitions written: {steps_path}[/green]")

        # Write environment.py with before_all hook
        _write_environment_file(base_url)

        # Show a preview
        console.print("\n[bold]Step definitions preview:[/bold]")
        syntax = Syntax(raw_code[:1500], "python", theme="monokai", line_numbers=True)
        console.print(syntax)
        if len(raw_code) > 1500:
            console.print("[dim]... (truncated for display)[/dim]")

        return {
            **state,
            "feature_file_path": str(feature_path),
            "steps_file_path": str(steps_path),
            "step_definitions": raw_code,
            "error": None,
            "current_node": "generate_steps"
        }

    except Exception as e:
        error_msg = f"Step generation failed: {e}"
        console.print(f"[red]❌ {error_msg}[/red]")
        return {**state, "error": error_msg, "current_node": "generate_steps"}


def _build_feature_file(scenarios: list[Scenario], api_spec: str) -> str:
    """Assembles a complete .feature file from approved scenarios."""
    # Extract a feature name from the spec (first line or fallback)
    first_line = api_spec.strip().splitlines()[0] if api_spec.strip() else "API"
    feature_name = first_line[:80].strip()

    lines = [
        f"Feature: {feature_name}",
        f"  # Auto-generated by BDD Agent",
        f"  # Approved scenarios: {len(scenarios)}",
        ""
    ]

    for scenario in scenarios:
        # Indent each line of the gherkin block by 2 spaces
        indented = "\n".join(
            f"  {line}" if line.strip() else ""
            for line in scenario["gherkin"].splitlines()
        )
        lines.append(indented)
        lines.append("")

    return "\n".join(lines)


def _write_environment_file(base_url: str) -> None:
    """Writes a Behave environment.py with before_all setup."""
    env_content = f'''"""
Behave environment hooks — auto-generated by BDD Agent.
"""
import requests


def before_all(context):
    """Set up shared context for all scenarios."""
    context.base_url = "{base_url}"
    context.session = requests.Session()
    context.response = None
    context.request_payload = {{}}


def after_all(context):
    """Tear down after all scenarios."""
    context.session.close()


def before_scenario(context, scenario):
    """Reset per-scenario state."""
    context.response = None
    context.request_payload = {{}}


def after_scenario(context, scenario):
    """Log scenario result."""
    status = "PASSED" if scenario.status == "passed" else "FAILED"
    print(f"  [{{status}}] {{scenario.name}}")
'''
    env_path = FEATURES_DIR / "environment.py"
    env_path.write_text(env_content, encoding="utf-8")
    console.print(f"[green]✅ environment.py written: {env_path}[/green]")


def _extract_base_url(api_spec: str) -> str:
    """
    Tries to extract a base URL from the API spec.
    Falls back to a placeholder if not found.
    """
    import re
    # Look for common patterns: "base_url", "host", "servers", URLs
    patterns = [
        r'https?://[^\s\'"<>]+',
        r'"host"\s*:\s*"([^"]+)"',
        r'base.?url["\s:=]+([^\s\'"]+)',
    ]
    for pattern in patterns:
        match = re.search(pattern, api_spec, re.IGNORECASE)
        if match:
            url = match.group(0) if "http" in match.group(0) else match.group(1)
            return url.rstrip("/")

    return "http://localhost:8000"
